name: Playwright Tests and Report Upload

on:
  push:
    branches: [ main ]  # adjust this to your needs
  pull_request:
    branches: [ main ]  # adjust this to your needs

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # adjust this to your Node.js version

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright browsers
      run: npx playwright install --with-deps

    - name: Run Playwright tests
      run: npx playwright test

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: playwright-report
        path: playwright-report/

    - name: Upload report to Uploadcare
      env:
        UPLOADCARE_PUBLIC_KEY: ${{ secrets.UPLOADCARE_PUBLIC_KEY }}
        UPLOADCARE_PRIVATE_KEY: ${{ secrets.UPLOADCARE_PRIVATE_KEY }}
      run: npx ts-node scripts/upload-report.ts
